name: Java CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      passed: ${{steps.info_step.outputs.passed}}
      failed: ${{steps.info_step.outputs.failed}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: Run tests
      run: mvn test
      id: info_step
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
  telegram_success:
    if: success()
    needs: [build]
    name: Telegram_success
    runs-on: ubuntu-latest
    steps:
        uses: actions/download-artifact@v4
        with:
          name: target_report
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            Status: All ${{steps.build.outputs.passed}} tests have passed
  telegram_failure:
    if: failure()
    needs: [build]
    name: Telegram_failure
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            Status: failing
            Status: ${{steps.build.outputs.passed}} tests have passed, ${{steps.build.outputs.failed}} tests have failed
