name: Java CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: Run tests
      run: mvn test
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: test-results
          path: tests-junit.xml
  telegram_success:
    if: success()
    needs: [build]
    name: Telegram_success
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            Status: passed
  telegram_failure:
    if: failure()
    needs: [build]
    name: Telegram_failure
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            Status: failing
